server:
  port: 8089

spring:
  application:
    name: JMP
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/JMP
    username: postgres
    driver: org.postgresql.Drive
  jpa:
    hibernate:
      cache:
        use_second_level_cache: true
        provider_class: net.sf.ehcache.hibernate.EhCacheProvider
      region:
        factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          provider_class: net.sf.ehcache.hibernate.EhCacheProvider

  liquibase:
    change-log: classpath:/db/changelog.xml
  thymeleaf:
    mode: LEGACYHTML5

logging:
  file:
    name: "src/main/resources/spring.log"


#  charset:
#    file: /Users/Anton_Tsyrkunou/Documents/SomeProject/JMP/jmpwep/src/main/logdir/log-file.log
#  file: /Users/Anton_Tsyrkunou/Documents/SomeProject/JMP/jmpwep/src/main/logdir/log-file.log

pdfdirectory: /Users/Anton_Tsyrkunou/Documents/SomeProject/JMP/jmpwep/src/main/resources